In [116]:
import gym
import numpy as np

In [118]:
env = gym.make("MountainCar-v0")
env.reset()

print(env.observation_space.high)
print(env.observation_space.low)
print(env.action_space.n)

SHOW_EVERY = 2000 # renderiza el ejercicio cada n cantidad e iteraciones
LEARNING_RATE = 0.1 # es una variable que se encuentra entre 0 y uno tambien se le puede dar decaimiento
DISCOUNT = 0.95 # que tan importantes son las acciones futuras sobre las actuales 
EPISODIOS = 25000

DISCRETE_SIZE = [20] * len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_SIZE


epsilon = 0.5 # entre 0 y 1  es la probabilidad de elegir una accion aleatoria 
START_EPSILON_DECAYING = 1
END_EPSILON_DECAYING = EPISODIOS // 2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING- START_EPSILON_DECAYING)

print(discrete_os_win_size)

## Variables Globales

q_table = np.random.uniform(low = -2, high = 0, size = (DISCRETE_SIZE + [env.action_space.n])) # esto me crea una tabla de 20x20xn donde n es el numero de acciones

ep_rewards = [] # guarda la recompenza de cada episodio
aggr_ep_rewards = {'ep' : [], 'avg': []}
print(q_table.shape)
print(q_table)



[0.6  0.07]
[-1.2  -0.07]
3
[0.09  0.007]
(20, 20, 3)
[[[-0.15101456 -0.1587285  -1.05598123]
  [-1.22311042 -1.77474013 -0.47761536]
  [-0.67269916 -0.91232637 -1.22079422]
  ...
  [-1.60248171 -1.12727066 -1.56010288]
  [-0.04211997 -0.46064324 -0.2127863 ]
  [-0.10706263 -0.16036255 -1.12505661]]

 [[-0.2291424  -0.16744148 -1.60921957]
  [-0.57444306 -1.30057621 -1.71842178]
  [-1.17322386 -0.8460121  -0.0968068 ]
  ...
  [-1.76962703 -1.44412662 -0.34229715]
  [-0.58383729 -0.37371681 -0.14792167]
  [-1.65774797 -0.95987111 -1.98668785]]

 [[-0.75116898 -0.5183346  -1.33990091]
  [-0.74419328 -0.43109545 -1.68064321]
  [-1.22465583 -0.78225137 -0.721139  ]
  ...
  [-1.82961848 -0.2777867  -0.43580663]
  [-1.90333918 -0.41631499 -0.51646972]
  [-0.30424539 -0.24540879 -1.53748546]]

 ...

 [[-1.33476763 -0.84855374 -0.24310368]
  [-1.61754182 -1.67997076 -0.35274555]
  [-1.49577601 -0.28271378 -1.06969675]
  ...
  [-1.52612273 -1.84909658 -0.45366811]
  [-1.46698545 -0.39132977 -1.

In [119]:
def get_discrete_satate(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(int))




In [120]:
for episode in range(EPISODIOS):
    if episode % SHOW_EVERY == 0:
        render = True
    else:
        render = False
    discrete_state = get_discrete_satate(env.reset())
    done = False
    while not done:
        action = np.argmax(q_table[discrete_state])
        new_state, reward ,done, _ = env.step(action)

        new_discrete_state  = get_discrete_satate(new_state)
        if render:
            env.render() # esto lo hacemos para ver la evolucion del algoritmo cada n episodios

        if not done:
            max_future_q = np.max(q_table[new_discrete_state]) # le aplicaremos el descuento  max_future_q 
            current_q = q_table[discrete_state + (action, )]

            new_q = (1- LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)   # formula de
            q_table[discrete_state + (action,)] = new_q
        elif new_state[0] >= env.goal_position:
            print(f"Logramos el Objetivo en el episodio:{episode} ")
            q_table[discrete_state + (action, )] = 0

        discrete_state = new_discrete_state
    
    if END_EPSILON_DECAYING >= episode >= START_EPSILON_DECAYING:
        epsilon -= epsilon_decay_value
    
env.close()

Logramos el Objetivo en el episodio:512 
Logramos el Objetivo en el episodio:679 
Logramos el Objetivo en el episodio:680 
Logramos el Objetivo en el episodio:684 
Logramos el Objetivo en el episodio:686 
Logramos el Objetivo en el episodio:687 
Logramos el Objetivo en el episodio:690 
Logramos el Objetivo en el episodio:691 
Logramos el Objetivo en el episodio:692 
Logramos el Objetivo en el episodio:693 
Logramos el Objetivo en el episodio:725 
Logramos el Objetivo en el episodio:734 
Logramos el Objetivo en el episodio:735 
Logramos el Objetivo en el episodio:741 
Logramos el Objetivo en el episodio:743 
Logramos el Objetivo en el episodio:751 
Logramos el Objetivo en el episodio:758 
Logramos el Objetivo en el episodio:853 
Logramos el Objetivo en el episodio:863 
Logramos el Objetivo en el episodio:911 
Logramos el Objetivo en el episodio:917 
Logramos el Objetivo en el episodio:921 
Logramos el Objetivo en el episodio:932 
Logramos el Objetivo en el episodio:936 
Logramos el Obje

KeyboardInterrupt: 

In [136]:
env.close()